"""Subledger SDK: cross-language vectors, request shape against a local fake server, and capture-queue behavior."""

import json
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

import pytest

from atcn import (
    SDK_HEADER,
    SDK_VERSION,
    AtcnClient,
    CaptureQueue,
    ReceiptLinkClient,
    SubledgerClient,
    build_response_statement,
    canonicalize,
    countersign_payload,
    digest_of,
    execution_binding,
    ext,
    generate_key_pair,
    public_key_from_private,
    sign_statement,
    stable_key,
    verify_countersignature,
    verify_statement_signature,
)

VECTORS = json.loads((Path(__file__).resolve().parents[3] / "packages/subledger/test-vectors/vectors.json").read_text())


# ---------- Cross-language vectors (generated by packages/subledger/scripts/generate-test-vectors.ts) ----------


@pytest.mark.parametrize("case", VECTORS["statements"], ids=lambda c: c["input"]["response_type"])
def test_response_statement_matches_typescript(case):
    given = case["input"]
    statement = build_response_statement(
        given["receipt"],
        given["response_type"],
        given.get("fields"),
        given.get("note"),
        given.get("evidence"),
        given.get("corrections"),
        execution=given.get("execution"),
        issued_at=given.get("issued_at"),
        expires_at=given.get("expires_at"),
        refs=given.get("refs"),
    )
    assert statement == case["statement"]
    assert canonicalize(statement) == case["canonical"]
    assert digest_of(statement) == case["digest"]
    assert sign_statement(statement, VECTORS["private_key"]) == case["signature"]
    assert verify_statement_signature(statement, case["signature"], VECTORS["public_key"])
    assert not verify_statement_signature({**statement, "receipt_revision": statement["receipt_revision"] + 1}, case["signature"], VECTORS["public_key"])


def test_execution_binding_matches_typescript():
    vector = VECTORS["execution_binding"]
    assert execution_binding(vector["descriptor"]) == vector["binding"]


def test_countersignature_matches_typescript():
    vector = VECTORS["countersignature"]
    assert public_key_from_private(VECTORS["private_key"]) == VECTORS["public_key"]
    assert countersign_payload(vector["payload"], VECTORS["private_key"]) == vector["signature"]
    assert verify_countersignature(vector["payload"], vector["signature"], VECTORS["public_key"])
    assert not verify_countersignature({**vector["payload"], "version": 2}, vector["signature"], VECTORS["public_key"])


def test_stable_keys_match_the_typescript_format():
    assert stable_key("financial", "stripe", "evt_1") == "sl:financial:stripe:evt_1"
    long_key = stable_key("task", "x" * 300)
    assert long_key.startswith("sl:task:sha256:") and len(long_key) <= 200
    assert ext("job-42") == "ext:job-42"


# ---------- Fake API server ----------


class FakeApi:
    """Records requests and answers each with the next scripted (status, body); defaults to 200 {}."""

    def __init__(self):
        self.requests: list[dict] = []
        self.responses: list[tuple[int, dict]] = []
        fake = self

        class Handler(BaseHTTPRequestHandler):
            def _handle(self):
                length = int(self.headers.get("content-length") or 0)
                raw = self.rfile.read(length) if length else b""
                fake.requests.append({"method": self.command, "path": self.path, "headers": {k.lower(): v for k, v in self.headers.items()}, "body": raw.decode("utf-8")})
                status, body = fake.responses.pop(0) if fake.responses else (200, {})
                data = json.dumps(body).encode("utf-8")
                self.send_response(status)
                self.send_header("content-type", "application/json")
                self.send_header("content-length", str(len(data)))
                self.end_headers()
                self.wfile.write(data)

            do_GET = do_POST = do_DELETE = _handle

            def log_message(self, *args):
                pass

        self.server = ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self.base_url = f"http://127.0.0.1:{self.server.server_address[1]}"
        threading.Thread(target=self.server.serve_forever, daemon=True).start()

    def json_body(self, index: int) -> dict:
        return json.loads(self.requests[index]["body"])


@pytest.fixture
def api():
    fake = FakeApi()
    yield fake
    fake.server.shutdown()


def error(status: int, code: str, retryable: bool) -> tuple[int, dict]:
    return status, {"error": {"code": code, "message": code, "retryable": retryable}}


def test_operator_client_uses_api_key_and_stable_idempotency_keys(api):
    client = SubledgerClient(api.base_url, "atcn_test_key", retries=0)
    client.create_task({"external_ref": "job-42", "currency": "USD"})
    client.get_task(ext("job-42"))
    client.record_financial_event({"type": "charge", "source": "stripe", "source_event_id": "ch_1", "amount_minor": 100, "currency": "USD", "event_date": "2026-10-01T00:00:00.000Z"})
    client.import_csv("type,source\n")

    create, get, charge, csv = api.requests
    assert create["headers"]["authorization"] == "Bearer atcn_test_key"
    assert create["headers"]["idempotency-key"] == "sl:task:job-42"
    assert get["path"] == "/v1/tasks/ext%3Ajob-42"
    assert "idempotency-key" not in get["headers"]
    assert charge["headers"]["idempotency-key"] == "sl:financial:stripe:ch_1"
    assert csv["headers"]["content-type"] == "text/csv"
    assert csv["body"] == "type,source\n"


def test_every_request_names_the_sdk_version_and_carries_default_headers(api):
    client = SubledgerClient(api.base_url, "k", retries=0, default_headers={"atcn-workflow": "demo"})
    client.get_task("tsk_1")
    ReceiptLinkClient(api.base_url, "share-token", retries=0).current()
    pyproject = (Path(__file__).resolve().parents[1] / "pyproject.toml").read_text()
    assert f'version = "{SDK_VERSION}"' in pyproject
    for request in api.requests:
        assert request["headers"][SDK_HEADER] == f"python/{SDK_VERSION}"
    assert api.requests[0]["headers"]["atcn-workflow"] == "demo"


def test_offering_an_obligation_for_a_task_sends_the_link_outside_the_signed_event(api):
    client = AtcnClient(api.base_url, "atcn_test_key", retries=0)
    signed = {"payload": {"event_id": "evt_1", "event_type": "obligation.offered"}, "signature": {"value": "sig"}}
    client.create_obligation(signed, {"task_id": "ext:job-42"})
    client.create_obligation(signed)

    linked, plain = api.json_body(0), api.json_body(1)
    assert linked == {**signed, "subledger": {"task_id": "ext:job-42"}}
    assert plain == signed
    assert api.requests[0]["headers"]["idempotency-key"] == "event:evt_1"


def test_countersign_signs_locally_and_sends_only_the_signature(api):
    private_key, public_key = generate_key_pair()
    client = SubledgerClient(api.base_url, "atcn_test_key", retries=0)
    closure = {"payload": {"closure_id": "cls_1", "version": 1}, "signature": {}}
    client.countersign(closure, "ops-1", private_key)
    sent = api.json_body(0)
    assert api.requests[0]["path"] == "/v1/closures/cls_1/countersign"
    assert set(sent) == {"key_id", "signature"}
    assert verify_countersignature(closure["payload"], sent["signature"], public_key)
    client.countersign({"payload": {"receipt_id": "rcp_1"}, "signature": {}}, "ops-1", private_key)
    assert api.requests[1]["path"] == "/v1/receipts/rcp_1/countersign"


def test_receipt_link_client_sends_the_share_token_instead_of_an_api_key(api):
    private_key, public_key = generate_key_pair()
    link = ReceiptLinkClient(api.base_url, "shr_tok_secret", retries=0)
    link.current()
    receipt = {"receipt_id": "rcp_1", "digest": "sha256:" + "a" * 64, "revision": 1}
    signing = {"binding_id": "pkb_1", "key_id": "prov-1", "private_key": private_key, "issuer_operator_id": "ten_1"}
    link.respond(receipt, "signed_attestation", ["delivery.status"], signing=signing)

    for request in api.requests:
        assert request["headers"]["x-atcn-share-token"] == "shr_tok_secret"
        assert "authorization" not in request["headers"]
    sent = api.json_body(1)
    assert sent["receipt_revision"] == 1 and sent["provider_signature"]["binding_id"] == "pkb_1"
    statement = build_response_statement({**receipt, "issuer_operator_id": "ten_1"}, "signed_attestation", ["delivery.status"])
    assert verify_statement_signature(statement, sent["provider_signature"]["value"], public_key)


def test_capture_queue_retries_with_one_key_and_never_raises(api):
    queue = CaptureQueue(SubledgerClient(api.base_url, "k", retries=0), max_size=3, max_attempts=2)
    assert queue.task({"external_ref": "job-1", "currency": "USD"})
    assert queue.financial_event({"type": "charge", "source": "stripe", "source_event_id": "ch_9", "amount_minor": 5, "currency": "USD", "event_date": "2026-10-01T00:00:00.000Z"})

    api.responses = [error(503, "retryable_infrastructure_failure", True)]
    assert queue.flush() == {"sent": 0, "failed": 0, "remaining": 2}
    assert queue.flush() == {"sent": 2, "failed": 0, "remaining": 0}
    keys = [r["headers"]["idempotency-key"] for r in api.requests]
    assert keys == ["sl:task:job-1", "sl:task:job-1", "sl:financial:stripe:ch_9"]


def test_capture_queue_overflow_failures_export_replay_and_gaps(api):
    queue = CaptureQueue(SubledgerClient(api.base_url, "k", retries=0), max_size=2, max_attempts=2)
    assert queue.task({"external_ref": "a", "currency": "USD"})
    assert queue.task({"external_ref": "b", "currency": "USD"})
    assert not queue.task({"external_ref": "c", "currency": "USD"})
    assert queue.dropped == 1 and queue.size == 2

    api.responses = [error(400, "validation_error", False)]
    assert queue.flush() == {"sent": 1, "failed": 1, "remaining": 0}
    exported = queue.export_failed()
    assert json.loads(exported)["idempotencyKey"] == "sl:task:a"
    assert queue.replay(exported) == 1 and queue.failed_operations() == []
    queue.flush()
    assert api.requests[-1]["headers"]["idempotency-key"] == "sl:task:a"

    assert queue.report_gaps(ext("job"))
    gap = api.json_body(len(api.requests) - 1)
    assert api.requests[-1]["path"] == "/v1/tasks/ext%3Ajob/capture-gaps"
    assert gap["kind"] == "queue_overflow" and "1 capture operation(s) dropped" in gap["detail"]


def test_capture_queue_survives_an_unreachable_api():
    queue = CaptureQueue(SubledgerClient("http://127.0.0.1:9", "k", retries=0, timeout=1), max_attempts=3)
    queue.task({"external_ref": "offline", "currency": "USD"})
    assert queue.flush() == {"sent": 0, "failed": 0, "remaining": 1}
    assert queue.failed_operations() == []
