"""Closure packages, task closures with their obligations' packages, and clearing verdicts give the same reports in
Python as in TypeScript (vectors generated by examples/local-runner/scripts/generate-package-vectors.ts)."""

import json
from pathlib import Path

import pytest

from atcn import verify_clearing_verdict, verify_closure_package, verify_subledger_document

VECTORS = json.loads((Path(__file__).resolve().parents[3] / "packages/core/test-vectors/closure-packages.json").read_text())
KEYS = VECTORS["trusted_keys"]


def names(cases: list[dict]) -> list[str]:
    return [case["name"] for case in cases]


@pytest.mark.parametrize("case", VECTORS["packages"], ids=names(VECTORS["packages"]))
def test_package_reports_match_typescript(case):
    options = case["options"]
    traces = [trace.encode("utf-8") for trace in options["traces"]] if "traces" in options else None
    assert verify_closure_package(case["package"], options.get("trusted_keys", KEYS), traces) == case["report"]


@pytest.mark.parametrize("case", VECTORS["closures"], ids=names(VECTORS["closures"]))
def test_closure_reports_with_obligation_packages_match_typescript(case):
    report = verify_subledger_document(case["document"], KEYS, obligation_packages=case["obligation_packages"])
    links = next(c for c in report["checks"] if c["name"] == "obligation_links")
    assert links == next(c for c in case["report"]["checks"] if c["name"] == "obligation_links")
    assert report == case["report"]


@pytest.mark.parametrize("case", VECTORS["verdicts"], ids=names(VECTORS["verdicts"]))
def test_verdict_reports_match_typescript(case):
    assert verify_clearing_verdict(case["verdict"], case.get("trusted_keys", KEYS), case.get("closure_package")) == case["report"]


def test_the_vectors_cover_valid_and_failing_cases():
    for group in ("packages", "closures", "verdicts"):
        validity = {case["report"]["valid"] for case in VECTORS[group]}
        assert validity == {True, False}, group


def test_without_packages_links_are_not_cross_checked():
    case = next(c for c in VECTORS["closures"] if c["obligation_packages"] is not None and c["report"]["valid"])
    report = verify_subledger_document(case["document"], KEYS)
    links = next(c for c in report["checks"] if c["name"] == "obligation_links")
    assert links["ok"] is True
    assert links["details"][0].endswith("closure packages not supplied; not cross-checked")
