"""Trace and pricing vectors (generated by packages/sdk-ts/scripts/generate-trace-fixtures.ts).

The Python SDK must give the same OpenTelemetry import, trace digests, usage summaries, trace problems, expected costs
and usage_cost details as the TypeScript SDK, byte for byte.
"""

import json
from pathlib import Path

import pytest

from atcn import (
    execution_binding,
    expected_cost_from_usage,
    summarize_trace,
    trace_digest,
    trace_from_otel_spans,
    trace_problems,
    usage_cost_details,
)

FIXTURES = json.loads((Path(__file__).resolve().parents[3] / "packages/sdk-ts/test-vectors/traces.json").read_text())
TRACES = {case["name"]: case["trace"] for case in FIXTURES["traces"]}


def test_execution_binding_matches_typescript():
    assert execution_binding(FIXTURES["descriptor"]) == FIXTURES["binding"]


def test_otel_import_matches_typescript():
    trace, skipped = trace_from_otel_spans(FIXTURES["otel"]["export"], FIXTURES["binding"])
    assert trace == FIXTURES["otel"]["trace"]
    assert skipped == FIXTURES["otel"]["skipped"]


def test_otel_import_refuses_an_export_without_genai_spans():
    with pytest.raises(ValueError, match="no GenAI model, tool or A2A spans"):
        trace_from_otel_spans({"resourceSpans": []}, FIXTURES["binding"])


@pytest.mark.parametrize("case", FIXTURES["traces"], ids=lambda c: c["name"])
def test_digest_and_summary(case):
    assert trace_digest(case["trace"]) == case["digest"]
    assert summarize_trace(case["trace"]) == case["summary"]
    assert trace_problems(case["trace"]) == []


def test_digest_ignores_whitespace_and_key_order():
    case = FIXTURES["traces"][0]
    reordered = json.loads(json.dumps(dict(reversed(list(case["trace"].items()))), indent=4))
    assert trace_digest(reordered) == case["digest"]


@pytest.mark.parametrize("case", FIXTURES["malformed"], ids=lambda c: c["name"])
def test_trace_problems(case):
    assert trace_problems(case["trace"]) == case["problems"]


@pytest.mark.parametrize("case", FIXTURES["cost_cases"], ids=lambda c: c["name"])
def test_expected_cost(case):
    summaries = [summarize_trace(TRACES[name]) for name in case["traces"]]
    assert expected_cost_from_usage(FIXTURES["pricings"][case["pricing"]], summaries) == case["expected"]


@pytest.mark.parametrize("case", FIXTURES["detail_cases"], ids=lambda c: c["name"])
def test_usage_cost_details(case):
    traces = [TRACES[name] for name in case["traces"]]
    assert usage_cost_details(FIXTURES["pricings"][case["pricing"]], case["amount_minor"], traces) == case["expected"]
