"""Adversarial attestation fixtures (generated by packages/verifiers/scripts/generate-attestation-fixtures.ts).

The Python SDK does not run verifier plugins; it checks that it reproduces the same signatures, payload digests,
and execution bindings, so a Python verifier or provider tool agrees with the TypeScript one byte for byte.
"""

import json
from pathlib import Path

import pytest

from atcn import digest_of, execution_binding, verify_payload

FIXTURES = json.loads((Path(__file__).resolve().parents[3] / "packages/verifiers/test-vectors/attestations.json").read_text())


def key_for(signature):
    return next(k for k in FIXTURES["keys"] if k["key_id"] == signature["key_id"] and k["key_version"] == signature["key_version"])


@pytest.mark.parametrize("case", FIXTURES["execution_bindings"], ids=lambda c: c["descriptor"]["execution_id"])
def test_execution_binding_matches_typescript(case):
    assert execution_binding(case["descriptor"]) == case["binding"]


@pytest.mark.parametrize("case", FIXTURES["plugin_cases"], ids=lambda c: c["name"])
def test_plugin_case_signature(case):
    signed = case["attestation"]
    assert verify_payload(signed, key_for(signed["signature"])["public_key"]) == case["expected"]["signature_valid"]


@pytest.mark.parametrize("case", FIXTURES["resolution_cases"], ids=lambda c: c["name"])
def test_resolution_case_references(case):
    digests = [digest_of(a["payload"]) for a in case["attestations"]]
    for signed in case["attestations"]:
        assert verify_payload(signed, key_for(signed["signature"])["public_key"])
    for problem in case["expected"]["problems"]:
        refs = case["attestations"][problem["attestation"]]["payload"]["refs"]
        targets = [ref["attestation_digest"] for ref in refs]
        if problem["target"] is None:
            assert not any(t in digests for t in targets)
        else:
            assert digests[problem["target"]] in targets
